### ISSUE TITLE
Generated entity id for new entity is not available after saving it

### ISSUE THREAD

**Issue by cocsackie** [Microsoft/spring-data-cosmosdb#112]
Given such entity and repository:

```java
@Document(collection = "tokens")
public final class Token {

    @Id
    private String id;
    private String userId;
    private OffsetDateTime expirationDate;

    public Token(String userId, OffsetDateTime expirationDate) {
        this.userId = userId;
        this.expirationDate = expirationDate;
    }

    private Token() {
    }

    public String getId() {
        return id;
    }

    public String getUserId() {
        return userId;
    }

    public OffsetDateTime getExpirationDate() {
        return expirationDate;
    }

    public void setId(String id) {
        this.id = id;
    }
}

public interface TokenRepository extends DocumentDbRepository<Token, String> {
}
```

When calling repository method save, and trying to get id of the entity:

`tokenRepository.save(new Token(user.getId(), offsetDateTime.now().plus(Duration.ofMinutes(10)))).getId()`

it returns null, while in the DocumentDB database, the entity has id (which is generated by the library).

It turns out, that id is available to the application in `DocumentDbTemplate`, but because it creates a copy of the document as `Document` and returns original entity object to the caller, id is not set.

**Quick and dirty solution:**

When in debug mode, executing:

`new DocumentDbEntityInformation(objectToSave.getClass()).getId().set(objectToSave, document.getId()) ` just before `DocumentDbTemplate.inseret(String, T, PartitionKey)` returns, solves the problem.

**Better solution - not tested though**
Because DocumentDbEntityInformation is available in SimpleDocumentDbRepository, which calls `DocumentDbOperations.insert`, we could pass entity id setter callback:

So instead of:

```java
<T> T insert(T objectToSave, PartitionKey partitionKey);
<T> T insert(String collectionName, T objectToSave, PartitionKey partitionKey);
```
we could have:
```java
<T, ID> T insert(T objectToSave, PartitionKey partitionKey, IdSetter idSetter);
<T> T insert(String collectionName, T objectToSave, PartitionKey partitionKey, IdSetter idSetter);

@FunctionalInterface
public interface IdSetter {

    public void setId(Object id);

    default IdSetter forField(Object entity, Field field) {
        return (id) -> ReflectionUtils.setField(field, entity, id);
    }

}
```

`SimpleDocumentDbRepository.save` - changed call to insert:

```java

documentDbOperations.insert(entityInformation.getCollectionName(),
                    entity,
                    createKey(entityInformation.getPartitionKeyFieldValue(entity)),
                    IdSetter.forField(entity, entityInformation.getId()));

```

Change DocumentDbTemplate.insert
to
```java
return insert(getCollectionName(objectToSave.getClass()),
                objectToSave,
                partitionKey,
                idSetter);
```
Add to DocumentDbTemplate.insert just before returning

```
idSetter.setId(document.getId())
```

**Comment by Incarnation-p-lee** [comment]
@cocsackie
Thanks for your time, could you please provide which version are you using ?

**Comment by cocsackie** [comment]
I'm using it with Spring Boot 2.0, I hope this is what you ask for:
documentdb-spring-boot-starter:2.0.1
spring-data-documentdb:2.0.1
azure-documentdb:1.13.0

**Comment by Incarnation-p-lee** [comment]
@cocsackie
Thanks a lot. I will try to reproduce it and fix it ASAP.
