### ISSUE TITLE
id is not necessary for the upsert operation

### ISSUE THREAD

**Issue by sophiaso** [Microsoft/spring-data-cosmosdb#115]
[source code link](https://github.com/Microsoft/spring-data-cosmosdb/blob/master/src/main/java/com/microsoft/azure/spring/data/documentdb/core/DocumentDbTemplate.java#L124-L150)

id is not necessary for a upsert operation and id is not used.

**Comment by Incarnation-p-lee** [comment]
done in PR https://github.com/Microsoft/spring-data-cosmosdb/pull/117
