### ISSUE TITLE
how to suppress null values in cosmos-db spring repository save method

### ISSUE THREAD

**Issue by senthilkrishnankr** [microsoft/spring-data-cosmosdb#141]
Hello,

I have a repository called "Shipment" which has following structure. I am noticing that Null values are not being suppressed when we try to insert using repository.save(shipmentObject) method. But Null values are being suppressed while using documentClient.upsertDocument(shipmentObject) method. how can we suppress null values being stored in cosmosDB  when we use springdata cosmosdb?

Code Snippet:
```java
Shipment shipment = new Shipment();
shipment.setShipementID(id);
Shipment sp = shipmentRepository.save(shipment); ==> null values being stored in "shipmentmessage" field
documentClient.upsertDocument(shipment) ==> null values are not stored in  "shipmentmessage"  field

Shipment Repository Bean:
@JsonInclude(Include.NON_NULL)
@Document(collection = "shipment")
@DocumentIndexingPolicy(mode = IndexingMode.Lazy)
public class Shipment {
	@Id
	@JsonProperty("id")
String id;
String shipmentMessage;
...
}
```
```
Expected Output:
{
    "id": "436",
    "_rid": "Io1rAM1GtAAuAAAAAAAAAA==",
    "_self": "dbs/Io1rAA==/colls/Io1rAM1GtAA=/docs/Io1rAM1GtAAuAAAAAAAAAA==/",
    "_etag": "\"04001d06-0000-0000-0000-5b44304d0000\"",
    "_attachments": "attachments/",
    "_ts": 1531195469
}

Actual Output:
{
    "id": "436",
"shipmentMessage":null,
    "_rid": "Io1rAM1GtAAuAAAAAAAAAA==",
    "_self": "dbs/Io1rAA==/colls/Io1rAM1GtAA=/docs/Io1rAM1GtAAuAAAAAAAAAA==/",
    "_etag": "\"04001d06-0000-0000-0000-5b44304d0000\"",
    "_attachments": "attachments/",
    "_ts": 1531195469
}
```

Please let me know if you need additional details.

**Comment by Incarnation-p-lee** [comment]
@senthilkrishnankr 
Thanks for you issue. The implementation of this repo keep null here for keep the consistency between entity in database and java instance. But it seems the client will eliminate the null when persistent. Could u please share why you need to suppress null ? or what problem the null value brings to u ?

**Comment by senthilkrishnankr** [comment]
Thanks for reaching out to me. we don't face any functionality issue so far. But it occupies some space in the database. For my case, our shipment repository will have 30-40 columns. almost 60% of the columns value would be null when we insert data. It may get value as and when shipment progress. Sometimes it won;t have data for 60% columns. So If we suppress null values ,then I would save some space in the cosmos DB. Earlier we were using mongodb and now we are migrating towards cosmos DB. But Mongo DB did not store null values in the database while using spring data Mongo DB repository.save() method.

**Comment by kushagraThapar** [comment]
@senthilkrishnankr Are you still facing this issue ?

**Comment by mohitmate** [comment]
@kushagraThapar : This issue is still there. It will be useful if we could have support to suppress null fields

**Comment by kushagraThapar** [comment]
@mohitmate - I will take a look at this soon. Now since the repo has been moved here: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-spring-data-cosmos
I have created this issue and tracking it here and closing this one: https://github.com/Azure/azure-sdk-for-java/issues/13307
