### ISSUE TITLE
Cant call self href directly for Entity

### ISSUE THREAD

**Issue by emthomas** [Microsoft/spring-data-cosmosdb#193]
I am using the following:

      <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.1.RELEASE</version>
		<relativePath/> 
	</parent>

        <dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>spring-data-cosmosdb</artifactId>
			<version>2.0.3</version>
	</dependency>

http://localhost:8080/api/questionSimilarities/51847986
When I try to use the href above for one of my entity I get the following error message: 

    {"timestamp":"2018-08-24T00:57:35.070+0000","status":500,"error":"Internal Server     Error","message":"PartitionKey value must be supplied for this operation.","path":"/api/questionSimilarities/51847986"}

The message is pretty clear. and the question is how do I pass this? I know I can re-implement to get what I need, but that doesn't sound right to me.

Below you can see my Entity is present.
![image](https://user-images.githubusercontent.com/7446317/44559381-877fbe00-a6fe-11e8-9df7-cbb64e7c6f29.png)

Model code:
![image](https://user-images.githubusercontent.com/7446317/44559406-bdbd3d80-a6fe-11e8-8453-93b177eca06b.png)

Any help would be appreciated.

Thanks!

**Comment by Incarnation-p-lee** [comment]
This error should be querying with incorrect configuration of partitionKey. I will try to reproduce from my side later.

**Comment by Incarnation-p-lee** [comment]
@emthomas 
About this issue, I think the failure should be apply both `@Id` and `@PartitionKey` to  `id` field in domain Class. I am not locating the doc that is invalid in cosmosdb, but that may not the recommended practice of query. The sdk side for some API like `findById` didn't export the option for set partitionKey. So here I suggest that you can apply `@PartitionKey` to some field else. One field with both `PartitonKey` and `@Id` may makes only one entry for each table.

Any question or help please reply me directly. Thanks again.

**Comment by Incarnation-p-lee** [comment]
@emthomas 
There seems one way to fix this from the server-sdk, I will try it if works well. But you'd better not apply both Annotation in one field.

**Comment by Incarnation-p-lee** [comment]
@emthomas 
The PR has been merged to master tree, Cloud you please help to take a try ?

**Comment by emthomas** [comment]
Yes. I will try tomorrow and report back. Thanks

**Comment by emthomas** [comment]
@Incarnation-p-lee I finally have a chance to try this. But when you say it has been merged to master, do I need to pull master and rebuild the library? I am using the package from maven. is there a new version? 

I am currently using 
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>spring-data-cosmosdb</artifactId>
			<version>2.0.3</version>
		</dependency>

**Comment by Incarnation-p-lee** [comment]
@emthomas 
We release new version of 2.0.4, cloud you please have a try there ?
