### ISSUE TITLE
If the uri for a cosmosdb has a path, it is lost

### ISSUE THREAD

**Issue by bkwilson** [Microsoft/spring-data-cosmosdb#220]
When the uri for the cosmosdb is host/path/path the /path/path part is discarded during initial setup of spring.

I was able to step through with the debugger during the startup of the app and manually set the uri to the full thing, doing this made everything worked as expected, so I think this is a bug.

**Comment by Incarnation-p-lee** [comment]
@bkwilson 
Thanks for try spring-data-comosdb, cloud you please share more information with sample to reproduce this issue, the URI is feed to sdk directly. Looks we may need to wrapper this for this issue.

**Comment by bkwilson** [comment]
Usually the uri will look something like https://xxxx.documents.azure.com:443/, however my workplace infrastructure needs everything to go through Kong - meaning the uri that has been setup is https://api.dev.xxxx.com/service/azureblahblah/v1 etc (with a upstream uri of https://xxxx.documents.azure.com:443/)  the /service/azureblahblah/v1 part is discarded and only api.dev.xxxx.com is used, meaning the wrong uri is hit.

I was able to hit the https://api.dev.xxxx.com/service/azureblahblah/v1  endpoint directly using curl/postman with the correct headers needed by cosmosdb and it all works that way, so there is not a problem with the setup. It is just the path is lost.

**Comment by bkwilson** [comment]
We were able to work around the issue by creating a url without a path - so at this stage everything is working fine, dont worry about it
