### ISSUE TITLE
Migrate DocumentDbOperations from Sync and Async

### ISSUE THREAD

**Issue by Incarnation-p-lee** [Microsoft/spring-data-cosmosdb#241]
### Operations
* [x] __deprecated__  ~~<T> List<T> findAll(Class<T> entityClass);~~
* [x] findAll(String collectionName, Class<T> entityClass, String partitionKeyName)
* [x] __deprecated__ ~~<T> T findById(Object id, Class<T> entityClass);~~
* [x] ```<T> Optional<T> findById(String collectionName, Object id, Class<T> entityClass);```
* [x]  __deprecated__ ~~<T> T insert(T objectToSave, PartitionKey partitionKey);~~
* [x] ```<T> T insert(String collectionName, T objectToSave, PartitionKey partitionKey);```
* [x] __deprecated__ ~~<T> void upsert(T object, PartitionKey partitionKey);~~
* [x] ```<T> void upsert(String collectionName, T object, PartitionKey partitionKey);```
* [x] ```<T> void deleteById(String collectionName, Object id, PartitionKey partitionKey);```
* [x] ```void deleteAll(String collectionName, Class<?> domainClass);```
* [x] void deleteCollection(String collectionName);
* [x] <T> List<T> delete(DocumentQuery query, Class<T> entityClass, String collectionName);
* [x] <T> List<T> find(DocumentQuery query, Class<T> entityClass, String collectionName);
* [x] <T> Boolean exists(DocumentQuery query, Class<T> entityClass, String collectionName);
* [x] <T> Page<T> findAll(Pageable pageable, Class<T> domainClass, String collectionName);
* [x] <T> Page<T> paginationQuery(DocumentQuery query, Class<T> domainClass, String collectionName);
* [x] long count(String collectionName);
* [x] <T> long count(DocumentQuery query, Class<T> domainClass, String collectionName);

### Repository
* [x] ```<S extends T> Observable<S> saveAsync(S domain);```
* [x] ```<S extends T> Observable<S> saveAllAsync(Iterable<S> entities);```
* [x] ```Observable<T> deleteAllAsync(Iterable<? extends T> entities);```
* [x] ```Observable<T> findAllByIdAsync(Iterable<ID> ids);```
* [x] ```Observable<T> findByIdAsync(ID id);```
* [x] ```Observable<Object> deleteByIdAsync(ID id);```
* [x] ```Observable<T> deleteAllAsync();```
* [x] ```Observable<Boolean> existsByIdAsync(ID id);```
* [x] ```Observable<Page<T>> findAllAsync(Pageable pageable);```
* [x] ```Observable<T> findAllAsync();```
* [x] ```Observable<T> findAllAsync(Sort sort);```
* [x] ```Observable<T> deleteAsync(T entity);```
* [x] ```Observable<Long> countAllAsync();```

**Comment by xscript** [comment]
Close this issue and track work item at #299 .
