### ISSUE TITLE
Inability to sort while paginating

### ISSUE THREAD

**Issue by TeoBanu** [Microsoft/spring-data-cosmosdb#270]
I am trying to sort while paginating on findAll and am not able to. 
I tried findAll with **sort** = new Sort(Sort.Direction.DESC, "createdAt"), and I get all the objects correctly sorted by the provided sort criteria. 
Then, I tried findAll with pageable, where pageble = new PageRequest(0, 5, **sort**), for which I get the first 5 objects, but not sorted by  "createdAt". In addition, DocumentDbPageRequest does not seem to have any means to set the sort. 
Is it possible to achieve this at the moment? How?

**Comment by Incarnation-p-lee** [comment]
@TeoBanu 
Thanks for trying spring-data-cosmosdb, I will try to reproduce from my env.

**Comment by sophiaso** [comment]
Hi @TeoBanu, thanks for reporting issue, it's not possible for existing released versions, we have merged a [PR](https://github.com/Microsoft/spring-data-cosmosdb/pull/272), please wait for a new release. Or you can build a local snapshot version to have a try.

**Comment by TeoBanu** [comment]
Thank you for taking the time to look into it.
