### ISSUE TITLE
Unexpected Error: PartitionKey value must be supplied for this operation.

### ISSUE THREAD

**Issue by ttworek** [Microsoft/spring-data-cosmosdb#317]
I'm trying out the very basic example as shown in the README/frontpage of this repo.  I am able to get my User object to get saved into the database, but upon retrieving it, I get the following exception:

```text
There was an unexpected error (type=Internal Server Error, status=500).
PartitionKey value must be supplied for this operation.
java.lang.UnsupportedOperationException: PartitionKey value must be supplied for this operation.
	at com.microsoft.azure.documentdb.DocumentClient.addPartitionKeyInformation(DocumentClient.java:3349)
...
```

My code is as follows:

```xml
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>spring-data-cosmosdb</artifactId>
    <version>2.1.0</version>
</dependency>
```

```java
@Configuration
@EnableDocumentDbRepositories
public class CosmosConfiguration extends AbstractDocumentDbConfiguration
{
    @Value("${azure.cosmosdb.uri}")
    private String uri;

    @Value("${azure.cosmosdb.key}")
    private String key;

    @Value("${azure.cosmosdb.database}")
    private String dbName;

    public DocumentDBConfig getConfig()
    {
        return DocumentDBConfig.builder(uri, key, dbName).build();
    }
}
```

```java
@Controller
@RequestMapping("/cosmos")
public class CosmosController
{
    @Autowired
    private final CosmosUserRepository cosmosUserRepository;

    @GetMapping("/user")
    public String getUser(final Model model)
    {
        cosmosUserRepository.deleteAll();

        final User user = new User(UUID.randomUUID().toString(), "John", "Doe");

        cosmosUserRepository.save(user);

        final User foundUser = cosmosUserRepository.findById(user.getId()).orElse(null);

        model.addAttribute("user", foundUser);

        return "cosmos/user";
    }
}


@Repository
public interface CosmosUserRepository extends DocumentDbRepository<User, String>
{
}
```
```java
@Data
@AllArgsConstructor
@NoArgsConstructor
public class User
{
    private String id;
    private String firstName;
    @PartitionKey
    private String lastName;
}
```

Specifically, the exception is thrown at:
```java
        final User foundUser = cosmosUserRepository.findById(user.getId()).orElse(null);
```

The main page says
> Supports Azure Cosmos DB partition. To specify a field of domain class to be partition key field, just annotate it with @PartitionKey. When you do CRUD operation, pls specify your partition value. For more sample on partition CRUD, pls refer to test here

but the link is broken to the example of how to specify your partition key value

**Comment by Incarnation-p-lee** [comment]
@ttworek 
Thanks for your issue. From the information and code in below, if you add partitionKey in domain field, only the id cannot identify the unique instance from cosmosdb. You should add partitionKey field when query for the unique instance. This is quit different to the concept of spring data.

So here, if you want to find the instance from you code, you may need to add one query in your repository like this:
```java
List<User> findByIdAndLastname(String id, String lastname);
```

And then in your controller, you can leverage this method for query with partitionKey.
```java
repository.findByIdAndLastname(xxx, xxx);
```

**Comment by ttworek** [comment]
Great, thanks for the help, that solved the issue!

The docs on the front page need to be updated though. They mention this case, but the example/explanation of how to solve it refers to a broken link

**Comment by Incarnation-p-lee** [comment]
@ttworek 
Yes, we will update the doc ASAP.

**Comment by isaac-ipl** [comment]
@Incarnation-p-lee 
I'm a bit confused with the partition key requirement. What happens if we want to list all users by first name only?
