### ISSUE TITLE
Partition key length limit is allowed upto max 100 char length

### ISSUE THREAD

**Issue by saurabhtanwar180896** [microsoft/spring-data-cosmosdb#321]
when Partition key length is greater than 100 char length , getting error 
insert exception; nested exception is com.microsoft.azure.documentdb.DocumentClientException: Message: {\"Errors\":[\"PartitionKey extracted from document doesn't match the one specified in the header\"]} 
But in CosmosDB SDK to v2.1.0 #4008 it was fixed. please look for this

azure cosmos  db partition key length issue fixed : https://github.com/Azure/azure-cosmosdb-java/issues/63

**Comment by Incarnation-p-lee** [comment]
Thanks for issue this. Our stable branch leverage azure cosmosdb sync sdk, and you mentioned sdk is for async.

We also have plan to support that but the async sdk leverage RxJava 1.x which is EOF for now.

**Comment by kushagraThapar** [comment]
@saurabhtanwar180896 - I believe this issue should be fixed in versions 2.1.7 and above. Closing this issue. 
Feel free to re-open if you still see issues.
