### ISSUE TITLE
Custom Gremlin Query And recursive object building

### ISSUE THREAD

**Issue by ss09201980** [microsoft/spring-data-cosmosdb#328]
Does the framework support executing complex queries and building vertex and edge hierarchies recursively ?

**Comment by Incarnation-p-lee** [comment]
@ss09201980 
Thanks for issue. This repo only focus on SQL API. If you want to leverage graph API of cosmosdb, you may need to take a look into this [spring-data-gremlin](https://github.com/Microsoft/spring-data-gremlin).
