### ISSUE TITLE
Pagination not working as expected

### ISSUE THREAD

**Issue by anshul-dhyani** [Microsoft/spring-data-cosmosdb#348]
I am trying to achieve limit functionality but it is not implemented yet in the artifact.
In order to achieve limit functionality I am trying to use pagination and sorting.
to get one page with 1 record but still it returns all the documents satisfying the query criteria (ignoring pagination)

**Comment by Incarnation-p-lee** [comment]
@anshul-dhyani 
Thanks for issue this, could you please help to share some more details about this, like version, spring boot version, as well as minimal reproduce code ? So we can try to reproduce that from our side.

**Comment by anshul-dhyani** [comment]
Below are the dependencies used:
        <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.3.RELEASE</version>
		<relativePath /> 
	</parent>

                <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

                <dependency>
		    <groupId>com.microsoft.azure</groupId>
		    <artifactId>spring-data-cosmosdb</artifactId>
		    <version>2.1.0</version>
		</dependency>

This is what my repository looks like :
@Repository
public interface MyRepo extends DocumentDbRepository<MyPOJO, String> {
	public List<MyPOJO> findByName(String name, Pageable pageable);
	
}

method in my rest controller
findByName("name", new DocumentDbPageRequest(0, 1, null, new Sort(Direction.DESC, "_ts")));

expectations:
[ MyPOJO [id=id2, name=name ] ]

reality : 
[ MyPOJO [id=id2, name=name ],  MyPOJO [id=id1, name=name ],  MyPOJO [id=id1, name=name ] ]

**Comment by Incarnation-p-lee** [comment]
@sophiaso 
As paging related, could you please help to take a look for this issue ? Thanks a lot. 💯

**Comment by sophiaso** [comment]
@anshul-dhyani, according to the repository interface method you have shared:
`public List findByName(String name, Pageable pageable);`, to do paged query, the return type should be `Page<T>`,  i.e., the interface should be:
```
Page<MyPOJO> findByName(String name, Pageable pageable);
```

You can also refer to the integration test for [Repository](https://github.com/Microsoft/spring-data-cosmosdb/blob/master/src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/repository/PageableAddressRepository.java) and [How to use](https://github.com/Microsoft/spring-data-cosmosdb/blob/master/src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/PageableAddressRepositoryIT.java), thanks.

**Comment by anshul-dhyani** [comment]
Thanks for pointing this out.
