### ISSUE TITLE
Support partition key on nested object

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/spring-data-cosmosdb#350]
It is possible in Cosmos DB to set the partition key on a sub-object like so:

```json
{
    "path": {
        "to": {
            "partitionKey": "foo"
        }
    }
}
```

where the paths would be `["/path/to/partitionKey"]` in the collection settings.

In spring-data-cosmosdb, it appears you can only set it on the root object. 

Ideally, we could support setting it on a leaf node as in the above sample.

**Comment by Incarnation-p-lee** [comment]
Thanks for issue this. For now we only support at most one partitionKey from root Object.

**Comment by kushagraThapar** [comment]
Closing it here as this is being tracked in a separate repo.
