### ISSUE TITLE
IgnoreCase and AllIgnoreCase don't appear to function properly

### ISSUE THREAD

**Issue by jamesggraf** [microsoft/spring-data-cosmosdb#362]
When using the query builder mechanism in Spring Data, the `IgnoreCase` and `AllIgnoreCase` keywords don't appear to function properly. For example, creating a Repository with the following method signature successfully creates a function that queries by first name and last name, but does so in a case sensitive manner
`List<Person> findByLastnameAndFirstnameAllIgnoreCase(String lastname, String firstname);`

This signature should be supported as documented in Spring Data: https://docs.spring.io/spring-data/commons/docs/current/reference/html/#repositories.query-methods.details

Additionally Cosmos' SQL API appears to support the `lower()` function in its queries so adding support for this should be relatively simple?

**Comment by david-lpg** [comment]
When testing my program today I found the same problem... 8 months later. Could someone take a look on this? Thanks.

**Comment by kushagraThapar** [comment]
@david-lpg @jamesggraf I will take care of this in next release, sorry this got delayed.

**Comment by mkaczor** [comment]
Any update on that?

**Comment by kushagraThapar** [comment]
@mkaczor - I don't think so there is any update on this, tracking it now for new releases.

**Comment by kushagraThapar** [comment]
Closing it here as this is being tracked in a separate repo.
