### ISSUE TITLE
EnableCrossPartitionQuery Support

### ISSUE THREAD

**Issue by vigneshklncit** [microsoft/spring-data-cosmosdb#373]
How can i enable cross partition queries on my repositories in spring data?

I am getting error
com.microsoft.azure.documentdb.DocumentClientException: Cross partition query is required but disabled. Please set x-ms-documentdb-query-enablecrosspartition to true, specify x-ms-documentdb-partitionkey, or revise your query to avoid this exception.

**Comment by sophiaso** [comment]
@vigneshklncit Could you check whether [this document](https://github.com/microsoft/spring-data-cosmosdb/blob/master/QueryPartitionedCollection.md) helps?

**Comment by kushagraThapar** [comment]
Cross partition query is supported now in v2.1.8

**Comment by vigneshklncit** [comment]
Sure. Thanks.Will check
