### ISSUE TITLE
Use Optimistic lock with @Version annotation on _etag field

### ISSUE THREAD

**Issue by amanganiello90** [microsoft/spring-data-cosmosdb#378]
Hi all,
As said by #372 , how to implement the optimist lock in spring data? I have tried to use in my entity the _etag field (a cosmosdb system field updated automatically in every document changing explained in [cosmos concurrency microsoft guide](https://docs.microsoft.com/bs-latn-ba/azure/cosmos-db/database-transactions-optimistic-concurrency#optimistic-concurrency-control)) with spring data @Version annotation without any result.

**Comment by Incarnation-p-lee** [comment]
For now, this feature is not supported, and will add to our backlog.

**Comment by dsibilio** [comment]
@amanganiello90, @Incarnation-p-lee: opened PR #396 for a possible implementation

**Comment by amanganiello90** [comment]
I have tested it for me, and it's ok. @Incarnation-p-lee please review that and give feedbacks. Thanks

**Comment by Incarnation-p-lee** [comment]
@saragluna
Please help to review #396 .

**Comment by kushagraThapar** [comment]
The feature PR has been merged and will be released in 2.1.8, and any future versions. Closing this issue.
