### ISSUE TITLE
CI Pipeline not working

### ISSUE THREAD

**Issue by blackbaud-alanacable** [microsoft/spring-data-cosmosdb#388]
Hi,

I created a test PR (https://github.com/microsoft/spring-data-cosmosdb/pull/387) to see if the CI pipeline was working.  The tests are failing (https://travis-ci.org/microsoft/spring-data-cosmosdb/jobs/558000802) with the following error ```The input authorization token can't serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: 'get
colls
dbs/testdb-1/colls/PartitionPerson
fri, 12 jul 2019 19:40:34 gmt
'
ActivityId: 0d54cea0-5fdd-4af2-aed9-d960b19102ca, Microsoft.Azure.Documents.Common/2.4.0.0, StatusCode: Unauthorized```

Looks like it can not connect to Cosmos.  

Is there something we can do to help y'all get the pipeline working?

Thanks,
Alana

**Comment by Incarnation-p-lee** [comment]
Thanks for issue this, will investigate soon.

**Comment by xscript** [comment]
@saragluna could we double confirm that CI is fixed? If so, let's close this issue.
Thanks!

**Comment by saragluna** [comment]
CI's been fixed, close this issue.
