### ISSUE TITLE
Support SpEL expression resolution for @Document "collection" field

### ISSUE THREAD

**Issue by dsibilio** [microsoft/spring-data-cosmosdb#391]
It would be nice to be able to dynamically load a collection name using SpEL expressions.

Examples:
- from **property source**:
e.g.
```java
@Document(collection = "${dynamic.collection.name}")
public class MyCollection 
```
---
```java
@Document(collection = "#{@environment.getProperty('dynamic.collection.name')}")
public class MyCollection 
```
- from **bean** field/method invocation:
```java
@Document(collection = "#{@someBean.getCollectionName()}")
public class MyCollection 
```

## Pull Requests
https://github.com/microsoft/spring-data-cosmosdb/pull/390

**Comment by Thommynator** [comment]
Hi, this feature would be really helpful. 👍 
Right now I'm looking for away to make the collection name configurable by a property file like in the fist option.

I noticed that the pull request has merge conflicts. Are there any plans to add this feature in the near future? :) 

Can anyone tell me the best practice for making the collection name configurable without this change?

**Comment by dsibilio** [comment]
> I noticed that the pull request has merge conflicts.

Thanks for noticing, I pulled the changes and solved the conflicts. The Travis CI pipeline for integration tests seems to be broken though :(

> Can anyone tell me the best practice for making the collection name configurable without this change?

Without this feature, I think you'd have to work with changing the collection name reflectively at runtime (e.g. https://www.baeldung.com/java-reflection-change-annotation-params)

**Comment by christopheranderson** [comment]
@kushagraThapar - can you take a look at this?

**Comment by kushagraThapar** [comment]
@dsibilio I have moved the travis CI to Azure DevOps CI, which supports running the CI on PRs from forked repository. 
I have tried running that on your PR, but there are still some hiccups. I will fix that asap.

**Comment by dsibilio** [comment]
@kushagraThapar Thank you, let me know if I can help you with anything.

**Comment by kushagraThapar** [comment]
@dsibilio CI is running successfully on external PRs now. I will take a look at the PR tomorrow.
