### ISSUE TITLE
How to pass Custom ConnectionPolicy to build DocumentDBConfig?

### ISSUE THREAD

**Issue by swagulkarni** [microsoft/spring-data-cosmosdb#400]
Hi,

The OOTB DocumentDBConfig class has static methods to build the DBConfig but it uses the default ConnectionPolicy.

public static DocumentDBConfigBuilder builder(String uri, String key, String database) {
        return defaultBuilder()
                .uri(uri)
                .key(key)
                .database(database)
                .connectionPolicy(**ConnectionPolicy.GetDefault()**)
                .consistencyLevel(ConsistencyLevel.Session);
    }

We want the ability to write out own custom connectionPolicy while creating the DBConfig.

How can that be achieved?

**Comment by saragluna** [comment]
@swagulkarni you can customize your connectionPolicy as code shown below:

```java
DocumentDBConfig dbConfig = DocumentDBConfig.builder(dbUri, dbKey, dbName).build();
dbConfig.getConnectionPolicy().setConnectionMode(ConnectionMode.DirectHttps);
dbConfig.getConnectionPolicy().setMaxPoolSize(1000);
...
```

**Comment by swagulkarni** [comment]
Thanks, thats helpful.

**Comment by Incarnation-p-lee** [comment]
@saragluna 
As some users ask for this, can we add this to our readme about this ?

**Comment by saragluna** [comment]
Will update the readme, close this issue.
