### ISSUE TITLE
Reactive support for Cosmos DB

### ISSUE THREAD

**Issue by abhi2june** [microsoft/spring-data-cosmosdb#404]
Need help in alternative of org.springframework.data.mongodb.repository.ReactiveMongoRepository<T,ID> 
[link](https://github.com/spring-projects/spring-data-mongodb/blob/master/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/repository/ReactiveMongoRepository.java)

for Cosmos Db

**Comment by saragluna** [comment]
Thanks for reaching out to us. Actually we have been working on this feature for a while. Hope to release this feature soon.

**Comment by saragluna** [comment]
#394 has been merged. Close this issue.
