### ISSUE TITLE
DocumentBulkExecutor support for bulk delete and update

### ISSUE THREAD

**Issue by Yishagerew** [microsoft/spring-data-cosmosdb#407]
Hi, 
As far as I see, there is no support for BulkExecutor in spring data, and we are planning to use spring-data for cosmosDB without relying directly on DocumentClient.

Can we add it in the issue catalog?

**Comment by christopheranderson** [comment]
We're working on a new bulk utility for the azure-cosmos library that should "just work" with Spring, just need to expose the throughput optimized vs latency optimized switch we have planned.

**Comment by atulpratul** [comment]
Hi, 
Do we have any update on this?

**Comment by kushagraThapar** [comment]
@atulpratul  - yes, bulk operations are currently in development and planned to get delivered around May end. Once they are production ready in cosmos SDK, they will be exposed through spring-data-cosmsodb.

**Comment by kushagraThapar** [comment]
Closing it here as this is being tracked in a separate repo.
