### ISSUE TITLE
NoClassDefFoundError with Spring Boot 2.2.0.M5: IsNewStrategyFactory

### ISSUE THREAD

**Issue by denisw** [microsoft/spring-data-cosmosdb#409]
The `IsNewStrategyFactory` interface was [removed in Spring Data 2.2](https://github.com/spring-projects/spring-data-commons/commit/0bf160eb971819ea64bed92c5bc1fa323fd5f2b7#diff-d554d04fc731ed8b3550029e3a7ae310).

**Comment by christopheranderson** [comment]
Thanks for reporting this. We're working on aligning once RC1 is shipped, but might do a Milestone sooner.

**Comment by kushagraThapar** [comment]
We have fixed this in our current release cycle. New version v2.2.0 will be out in a couple of days.
