### ISSUE TITLE
Async Java SDK for DocumentDB (SQL API)

### ISSUE THREAD

**Issue by Matthew-Dong** [Microsoft/spring-data-cosmosdb#41]
Async Java SDK for DocumentDB (SQL API) is just released to support asynchronous operations. 

https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-async-java

**Comment by zhouchong90** [comment]
Is there any planned support to integrate async repositories?
Such as
Flux<User> findByFirstname

**Comment by erikthered** [comment]
Would you be open to a PR for this?

**Comment by zhouchong90** [comment]
Yes. Sure! I'll start working on it. Is there any documentation about PRs that I need to follow?

**Comment by erikthered** [comment]
I was interested in working on the possible PR, I am not affiliated with this project.

**Comment by xscript** [comment]
Close this issue and track work item at #299 .
