### ISSUE TITLE
ropertyReferenceException: No property saveAll found for type

### ISSUE THREAD

**Issue by rishits85** [microsoft/spring-data-cosmosdb#410]
While using spring data cosmos db version 2.1.2 I am getting the following error

Caused by: org.springframework.data.mapping.PropertyReferenceException: No property saveAll found for type MyType

Below is my class: 

```
@Repository
public interface Myrepo extends DocumentDbRepository<MyType, String> {

    public MyType findBySomeType(String someType);

    public List<MyType> saveAll(List<MyType> myType);
}
```
This happens only for the saveAll method. If I do the save method it works fine. What am I missing?

**Comment by rishits85** [comment]
Figured out the issue. I had overridden the method saveAll in my interface which is already implemented in the CRUDRespository interface extended by DocumentDBREpository

**Comment by rishits85** [comment]
Figured out the issue. I had overridden the method saveAll in my interface which is already implemented in the CRUDRespository interface extended by DocumentDBREpository

**Comment by nsaftarli** [comment]
> Figured out the issue. I had overridden the method saveAll in my interface which is already implemented in the CRUDRespository interface extended by DocumentDBREpository

Did you get to the bottom of why this works? I'm having the same problem, except I'm subclassing `CrudRepository` directly. I've overridden other methods (e.g. `save`, `findAll`), but only `saveAll` is causing this problem for me. Your fix works, but I'm not sure why.
