### ISSUE TITLE
Does this project support querydsl?

### ISSUE THREAD

**Issue by thiner** [microsoft/spring-data-cosmosdb#441]
queryDSL is very important for complex query. Do you have any plan to support?

**Comment by kushagraThapar** [comment]
> queryDSL is very important for complex query. Do you have any plan to support?

Yes, we plan to support it soon. Actual timeline for the release may happen around February. 
Until then, a workaround for executing complex queries can be found in the test examples: 

https://github.com/microsoft/spring-data-cosmosdb/blob/master/src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/PageableAddressRepositoryIT.java#L158
