### ISSUE TITLE
2.2.0 release not available in maven repository

### ISSUE THREAD

**Issue by rsahani** [microsoft/spring-data-cosmosdb#450]
Hi Team,
I see that we have a release version for 2.2.0. Can we get an ETA on when do we expect this to be pushed to mvn central repository(https://mvnrepository.com/artifact/com.microsoft.azure/spring-data-cosmosdb).

**Comment by kushagraThapar** [comment]
@rsahani not sure why the maven hasn't updated it, but I can see the new version here: 
https://repo1.maven.org/maven2/com/microsoft/azure/spring-data-cosmosdb/2.2.0/

**Comment by kushagraThapar** [comment]
@rsahani I see it here: https://mvnrepository.com/artifact/com.microsoft.azure/spring-data-cosmosdb/2.2.0
Closing this issue now.
