### ISSUE TITLE
spring-data-cosmosdb - Stored procedure, trigger support 

### ISSUE THREAD

**Issue by Akash08091992** [microsoft/spring-data-cosmosdb#456]
Does spring-data-cosmosdb library supports javascript azure portal Stored Procs, triggers or userdefined functions ?

**Comment by Akash08091992** [comment]
> Does spring-data-cosmosdb library supports javascript azure portal Stored Procs, triggers or userdefined functions ?

**Comment by kushagraThapar** [comment]
@Akash08091992 It does not support right now. To use that, please use Cosmos DB Java SDK here: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos
