### ISSUE TITLE
IN parameter is not supported ?

### ISSUE THREAD

**Issue by nagufriendly** [microsoft/spring-data-cosmosdb#457]
Is the findAllBy a list supported ?
Ex: List<Employee> findAllByNameIn(List<String> names)

**Comment by kushagraThapar** [comment]
@nagufriendly `IN` parameter should be supported. Here is one example: https://github.com/microsoft/spring-data-cosmosdb/blob/master/src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/ProjectRepositoryIT.java#L362

**Comment by kushagraThapar** [comment]
@nagufriendly - Are you still facing this issue ?
