### ISSUE TITLE
findAll with partition key

### ISSUE THREAD

**Issue by linux-code** [microsoft/spring-data-cosmosdb#471]
Is there any plan to have findAll method with partition key if someone wants to get all records within specific partition?

Thanks.

**Comment by linux-code** [comment]
Hi, 
Can someone update this?

**Comment by kushagraThapar** [comment]
@linux-code Hey Ghulam, I am trying to get answer for this one, and in fact for all the questions you have asked in the mail. Sorry for the delay in response. I will provide an update soon.

**Comment by kushagraThapar** [comment]
@linux-code I checked and it looks like this can be done in the next release, whenever that happens. 
Currently the schedule for next release looks around end of March. 
Meanwhile, I am also working on getting answers to your other questions.

**Comment by linux-code** [comment]
Sounds good. Thanks a lot.

**Comment by kushagraThapar** [comment]
@linux-code  Hey Ghulam, can you please verify if the linked PR fulfills your request ?

**Comment by kushagraThapar** [comment]
This has been released in spring-data-cosmosdb v2.2.3

**Comment by linux-code** [comment]
@kushagraThapar Gone through the PR , looks good to me.
