### ISSUE TITLE
SpringBoot Actuator for Azure CosmosDB

### ISSUE THREAD

**Issue by nsrags** [microsoft/spring-data-cosmosdb#490]
This is feature suggestion that can be incorporated as part of Spring Boot starter for CosmosDB.This will help us in healthchecking the CosmosDB and follow a similar approach for Boot Actuator.This would help in providing health stats from Spring Boot application standpoint for all its integrations (when CosmosDB is one among them)

**Comment by kushagraThapar** [comment]
Closing it here as this is being tracked in a separate repo.
