### ISSUE TITLE
Return entity collection saved by repository instead of input entity

### ISSUE THREAD

**Issue by amanganiello90** [microsoft/spring-data-cosmosdb#491]
Hi,
I noticed that the save api of the [SimpleDocumentDbRepository](https://github.com/microsoft/spring-data-cosmosdb/blob/75d5576d4b923aef1611e0b9fa656dde43b0c35e/src/main/java/com/microsoft/azure/spring/data/cosmosdb/repository/support/SimpleDocumentDbRepository.java#L85) return the input entity instead of saved entity. 
My purpose is to have the updated (or the new) entity with all database fields (such as the last _etag) in order to perform my business logic.

I don't want to execute a read of the entity after the save api 'cause of performance issues. So there is a way to do it, or any plans? Thanks

**Comment by kushagraThapar** [comment]
Thanks @amanganiello90 for opening this bug, I checked and confirmed this issue. 

I will fix it soon. 
Which version are you using ?

**Comment by amanganiello90** [comment]
I linked the class of the 2.1.9 version.

**Comment by kushagraThapar** [comment]
> I linked the class of the 2.1.9 version.

**Comment by kushagraThapar** [comment]
Thanks, closed this by mistake, reopened it. 
I will fix it. Can't promise the timeline, but will try to do it soon.

**Comment by kushagraThapar** [comment]
@amanganiello90 let me know if the above fixes look good to you. I plan to release them tonight.

**Comment by kushagraThapar** [comment]
spring-data-cosmosdb v2.1.10 and v2.2.3 has been released with this fix

**Comment by amanganiello90** [comment]
> 
> 
> spring-data-cosmosdb v2.1.10 and v2.2.3 has been released with this fix

Thanks, I will try it.
