### ISSUE TITLE
Standardize on either `collection` or `container`

### ISSUE THREAD

**Issue by jmax01** [microsoft/spring-data-cosmosdb#492]
Standardize on either `collection` or `container`.

Example: currently both `collectionName` or `containerName` are used throughout the API
for the values that are used by methods that return either [CosmosContainers](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/microsoft-azure-cosmos/src/main/java/com/azure/data/cosmos/CosmosContainer.java) or [CosmosSyncContainers](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/microsoft-azure-cosmos/src/main/java/com/azure/data/cosmos/sync/CosmosSyncContainer.java)

I would suggest standardizing on `container` over `collection` as that is terminology used in [azure-cosmos](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/microsoft-azure-cosmos).

* All current methods with `collection` naming should be deprecated
* All method parameters, local variables, and fields that contain `collection` should be updated to `container`
* The names of methods, method parameters, variables, and fields that refer to _container names_ and not `CosmosContainers` or `CosmosSyncContainer` should contain the word `name`.  Thus `ReactiveCosmosTemplate.collectionCache` should be `ReactiveCosmosTemplate.containerNameCache`.

**Comment by kushagraThapar** [comment]
Thanks for the suggestion @jmax01 We will standardize them to container throughout the SDK where breaking changes are not required. 
Regarding breaking changes, we can deprecate old APIs, and add new ones.

**Comment by kushagraThapar** [comment]
This has been released in spring-data-cosmosdb v2.2.3
