### ISSUE TITLE
Standardize on either `domainClass` or `entityClass`

### ISSUE THREAD

**Issue by jmax01** [microsoft/spring-data-cosmosdb#493]
Standardize on either `domainClass` or `entityClass`.

Example: https://github.com/microsoft/spring-data-cosmosdb/blob/d028e00ab92cc18da1f9ecb610a071c427f1c080/src/main/java/com/microsoft/azure/spring/data/cosmosdb/core/CosmosOperations.java#L55-L57

I would suggest that `domainType` actually would be the best term as this is the terminology that appears to be used in the `org.springframework.data.repository` package when referencing those domain `Class<?>` instances.

**Comment by kushagraThapar** [comment]
Thanks for the suggestion @jmax01 We will update those parameter names.

**Comment by kushagraThapar** [comment]
This is released in spring-data-cosmosdb v2.2.3
