### ISSUE TITLE
ISSUE - spring-data-cosmosdb - 2.2.2 version - @Id value is not autogenerated

### ISSUE THREAD

**Issue by sivawipro** [microsoft/spring-data-cosmosdb#508]
Currently I am using Spring data cosmosdb 2.1.0 version with Spring boot 2.1.7.RELEASE.
```
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>spring-data-cosmosdb</artifactId>
            <version>2.1.0</version>
        </dependency>
```
@Id field was autogenerated.

I would like to upgrade Spring data cosmosdb client:

```
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>spring-data-cosmosdb</artifactId>
    <version>2.2.2</version>
</dependency>
```

The issue i am facing is with @Id field, it's not autogenerating. It's saving as null in CosmosDB.

Can you please suggest why @Id field is not autogenerating. It's explicitly expecting me set value.

Kindly help.

Thanks.

**Comment by kushagraThapar** [comment]
@sivawipro  - `@id` is not autogenerated any more and is not supported by Cosmos DB SDK. 

Auto generate ID feature was removed in Cosmos DB SDK v3. You will need to generate id on your own.

**Comment by kushagraThapar** [comment]
Closing this issue now.
