### ISSUE TITLE
Support custom property field mapping

### ISSUE THREAD

**Issue by fritzfritz** [microsoft/spring-data-cosmosdb#51]
Motivation
- sometimes the naming of properties is not the same like for documents in the database
- I run specifically into issues with databases having capital field names in the JSON stored, then when constructing custom queries in repository interfaces it will query always for lower case fields 

Request
- make the JSON field configurable for which an attribute of the domain class, similar to @Field("fName") provided by the mongodb integration, see https://docs.spring.io/spring-data/data-mongo/docs/1.4.1.RELEASE/reference/html/mapping-chapter.html#mapping-usage-annotations

**Comment by sophiaso** [comment]
Hi @fritzfritz, thanks for reporting issue. Agree with  motivation `sometimes the naming of properties is not the same like for documents in the database`.

But about the issue in your motivation, could you share a sample POJO class and Repository interface to reproduce the issue you mentioned: `having capital field names and will query for lower case fields`? 

If there is one field `fName` defined in your POJO, custom query `findByFName(String fName)`
 should work as expected.

**Comment by elsesiy** [comment]
@sophiaso Your example is valid but this doesn't work with other naming conventions such aus `f_name` as this will be processed as `f`. I just ran into the same issue and it's quite an effort now to migrate the schema and remove the `_` just because there's not custom field mapping possible as of now.

**Comment by sophiaso** [comment]
@elsesiy Currently we do not have an ETA for this feature.

**Comment by kushagraThapar** [comment]
@elsesiy - I believe here is the work around for your issue if you are still facing it. 

https://github.com/microsoft/spring-data-cosmosdb/issues/536
