### ISSUE TITLE
[BUG] Full content scan in Cosmos DB from Spring

### ISSUE THREAD

**Issue by anfeldma-ms** [microsoft/spring-data-cosmosdb#511]
Posting on behalf of a customer. Unsure if the root cause is in Spring Data or Spring Boot.

**Customer Scenario**
The current customer Platform is being developed while leveraging SpringBoot as the Java platform layer. The current SpringBoot implementation causes a full scan and doesn't index properly.

**Customer Impact**
Additional context/code to manage. Our previous experience is with other tools that are able to support this in their data platforms.

**Current Mitigation**
Using the Java SDK instead of native spring boot functionality which is non standard per the framework as defined and introduces complexity.

Please let us know if there is any item planned to fix this issue.

**Comment by kushagraThapar** [comment]
@andfeldma-ms can you please share which customer is this ?

**Comment by anfeldma-ms** [comment]
@kushagraThapar I will follow up offline.

**Comment by kushagraThapar** [comment]
Closing it here as this is being tracked in a separate repo.
