### ISSUE TITLE
Reactive with Spring Data REST cosmos DB

### ISSUE THREAD

**Issue by tanayamitra05** [microsoft/spring-data-cosmosdb#529]
Is there any significant time difference for fetching data by using Flux in reactive and normal  List Collection in Java?

**Comment by tanayamitra05** [comment]
I am fetching the data like:
Flux<CentralizedManagementEntity> cmLogs = cmLogsRepository.findAll();
return cmLogs;

and the repository code:
public interface CMLogsRepository extends ReactiveCosmosRepository<CentralizedManagementEntity, String> {
    Flux<CentralizedManagementEntity> findAllById(String id);

But there is no such timing difference in this case.

**Comment by kushagraThapar** [comment]
@tanayamitra05 when you run reactive code like this : 
`Flux<T> cmLogs = cmLogsRepository.findAll();` it doesn't execute the find all operation at this point until you subscribe to it. So measuring timing at this point doesn't even makes sense. 

Please read project reactor docs for more details on how to run reactive asynchronous code. 
https://projectreactor.io/learn
