### ISSUE TITLE
querying lists of objects

### ISSUE THREAD

**Issue by chrisgolle** [microsoft/spring-data-cosmosdb#532]
Hello, i would like to write a query to find a nested property from a list of objects

`{id: "id", objects: [{"prop": "val1"},{{"prop": "val2"}}]}`

my query is the following:

`SELECT VALUE c FROM ROOT c join d in c.objects WHERE d.prop = @prop`

I can do this with a raw query, can i do it without?

**Comment by kushagraThapar** [comment]
Currently spring doesn't support query annotation feature, so for now the only option is to use the raw query. 
Here is a doc on how you can execute these raw queries in spring-data-cosmosdb : https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/how-to-guides-spring-data-cosmosdb#custom-query-execution

**Comment by chrisgolle** [comment]
ah, okay, thank you
