### ISSUE TITLE
Need the ability to Configure the Column Name With a Annotation Like we do in Spring Data JPA With @Column

### ISSUE THREAD

**Issue by chaitanya-mittapalli** [microsoft/spring-data-cosmosdb#536]
Need the ability to Configure the Column Name With a Annotation Like we do in Spring Data JPA With @Column

![image](https://user-images.githubusercontent.com/15993350/82472847-604e5000-9a8e-11ea-8bd2-4f04bfd5482b.png)

In the Above Entity I may Want to be the Column Name of the Field LastName to be last_name when a Document is generated in Cosmos Document DB. As of Now I do not see that ability with Spring Data cosmos

**Comment by chrisgolle** [comment]
it uses jackson object mapper underneath, so you can add jackson annotations to accomplish this.

**Comment by chaitanya-mittapalli** [comment]
Yup that is Working Thanks a TON @chrisgolle . Closing this Issue out

**Comment by kushagraThapar** [comment]
Thanks @chrisgolle
