### ISSUE TITLE
new spring data repo url in readme point to 404

### ISSUE THREAD

**Issue by Paizo** [microsoft/spring-data-cosmosdb#550]
the link to the new spring data cosmosdb repository points to https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-spring-data-cosmos which respond with 404

**Comment by zhoufenqin** [comment]
Hi @Paizo, we rename the azure-spring-data-cosmos to azure-spring-data-cosmos-core recently, the link is https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-spring-data-cosmos-core

**Comment by kushagraThapar** [comment]
Thanks @zhoufenqin for fixing the readme. 
@Paizo  thanks for pointing out this issue. This is fixed now.
