### ISSUE TITLE
Multiple DataSource(With CosmosDB) In Spring boot JPA

### ISSUE THREAD

**Issue by rannoune** [microsoft/spring-data-cosmosdb#554]
Hello,

I am in urgent need to connect to both Mysql and CosmosDB in my springboot application as we are incrementally migrating from mysql to cosmosdb. I checked the following link: https://github.com/microsoft/spring-data-cosmosdb/issues/403
But, I am using azure-cosmosdb-spring-boot-starter 2.3.5 and it does not work for me. I know @kushagraThapar mentioned that this will be supported in the next major version. Can you please let me know when the version will be released? And what workaround I can in the meanwhile implemented to make it work with the starter version 2.3.5?

Thank you

**Comment by kushagraThapar** [comment]
@rannoune - this is currently supported in azure-spring-data-cosmos v3.x.x 
@saragluna @chenrujun - can you please provide the timeline for when this will be available in spring boot starter ?

**Comment by chenrujun** [comment]
Hi, @rannounce,

Please use our latest version: https://repo.maven.apache.org/maven2/com/azure/spring/azure-spring-boot-starter-cosmos/3.0.0-beta.1/

Repo: https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter-cosmos_3.0.0-beta.1/sdk/spring/azure-spring-boot-starter-cosmos

**Comment by rannoune** [comment]
Thank you @kushagraThapar and @chenrujun for your quick response! We definitely want to use the springboot starter but since there is no stable version yet, we will use the azure-spring-data-cosmos v3.0.1 for now and then we can switch to the springboot starter once we have a non-beta version is available. @chenrujun do you have an estimate on when the first non-beta release is going to be out?

**Comment by kushagraThapar** [comment]
@rannoune - use - https://mvnrepository.com/artifact/com.azure/azure-spring-data-cosmos/3.1.0 3.1.0 version

**Comment by rannoune** [comment]
will do. Thank you!

**Comment by chenrujun** [comment]
@rannoune , we will release `azure-spring-boot-starter-cosmos` GA around mid of Dec.

**Comment by woodymoo** [comment]
@chenrujun  I tried the multidatabase samples on the folder which is new spring data cosmos release version 3.4.0,  but it does not work. can you please provide a complete sample with pom.xml ? 
  
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-spring-data-cosmos/src/samples/java/com/azure/spring/data/cosmos/multidatasource
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-spring-data-cosmos

**Comment by woodymoo** [comment]
Is there

> @chenrujun I tried the multidatabase samples on the folder which is new spring data cosmos release version 3.4.0, but it does not work. can you please provide a complete sample with pom.xml ?
> BTW, can I modify the connection uri information in RepositoryConfiguration and CosmosClient at runtime? to switch to another database at runtime?
> 
> https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-spring-data-cosmos/src/samples/java/com/azure/spring/data/cosmos/multidatasource
> https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-spring-data-cosmos

Is there any update? please, are you going to publish a complete multidatabase sample?

**Comment by chenrujun** [comment]
Hi, @yiliuTo , could you please help to investigate this issue? I remember that the feature(multidatabase) is developed by Fenqin.

**Comment by yiliuTo** [comment]
Hi @woodymoo , @lzc-1997-abel is working on the multi-database configuration sample and your questions. And he will update here when the sample is completed.

**Comment by lzc-1997-abel** [comment]
Hi @woodymoo, 
Here is the [multi-database configuration sample with multi account](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-cosmos-multi-database-multi-account), and here is the [multi-database with single account](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-cosmos-multi-database-single-account).If you wanner switch to another database at runtime, use different `ReactiveCosmosTemplate` and `CosmosTemplate`  might work.

**Comment by saragluna** [comment]
Closing this issue now since there's no update from the customer. Please reopen it if you have any further questions.
