### ISSUE TITLE
Exception while using 2 between clause

### ISSUE THREAD

**Issue by nitishsati82** [microsoft/spring-data-cosmosdb#557]
I am using comos db verion
<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-cosmosdb-spring-boot-starter</artifactId>
			<version>2.3.5</version>
		</dependency>

repository
public interface OrderRepository extends CosmosRepository<Name, String> {

	
	List<Name> findByNameAndTotalAmountBetweenAndOrderDateBetween(final String name,String amount1,String amount2,String date1,String date2);
	

}

exception 
[CIRCULAR REFERENCE:CosmosClientException{error={"code":"BadRequest","message":"Gateway Failed to Retrieve Query Plan: Message: {\"Errors\":[\"Invalid query. Specified duplicate parameter name '@start'.\"]}\r\nActivityId: 5ce51b6c-6b54-4c48-9489-99d10edf6e5e, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, StatusCode: BadRequest","additionalErrorInfo":null}, resourceAddress='null', statusCode=400, message=Gateway Failed to Retrieve Query Plan: Message: {"Errors":["Invalid query. Specified duplicate parameter name '@start'."]}

**Comment by saragluna** [comment]
Sorry for the late response, since we've deprecated this repo so I copied this issue to the new repo https://github.com/Azure/azure-sdk-for-java/issues/19653. We'll look into it and get back to you later.
