### ISSUE TITLE
Does @Transactional work on the repositories

### ISSUE THREAD

**Issue by sombhattacharyya1983** [microsoft/spring-data-cosmosdb#561]
This is more of a confirmatory query. 
So we are using version 2.1.2-Fix1 of the library for a Spring boot 2.1.9 based project.
We are looking for transactional behaviour. 
My understanding is we will not get any advantages of things like Rollback using the @Transactional on cosmos repos.
Is that a correct understanding ?

**Comment by kushagraThapar** [comment]
@sombhattacharyya1983 - yes, that is correct. `@Transactional` behavior is not supported for cosmos repos yet. 
Also, the project has been moved to a new repo, with latest spring-data-cosmos versions, please refer to readme - https://github.com/microsoft/spring-data-cosmosdb

**Comment by sombhattacharyya1983** [comment]
@kushagraThapar thank you for the clarification. I am considering migrating to the newer version as pointed by you. But am still not assuming transactional support. So if I need to to implement atomic updates across updates to diffrent containers I need to handle it myself.-

**Comment by kushagraThapar** [comment]
Yes, that is correct. For now, the transactional updates are not supported, but we have them planned in backlog for next semester. This new feature will come on the latest version, so it is important to migrate to the latest version of azure-spring-data-cosmos
