### ISSUE TITLE
unsupported keyword: BETWEEN (2): [IsBetween, Between]

### ISSUE THREAD

**Issue by rgong1987** [Microsoft/spring-data-cosmosdb#73]
Not sure if I am using it correctly, but I am getting this error while I am using
find by between Date range (milliseconds).

**Comment by Incarnation-p-lee** [comment]
@rgong1987 
Could you please share you sample code for reproducing? with documentdb version ? Thanks!

**Comment by rgong1987** [comment]
Hi @Incarnation-p-lee ,

It is something like `findByUserUuidAndStartBetween(String userUuid, String from, String to)` , I just saw the pull request regarding these keywords, so I guess it will be supported in the near future release ?

Thanks

**Comment by Incarnation-p-lee** [comment]
@rgong1987 
We will inform you when ready. Thanks!

**Comment by aaaabhishek13** [comment]
@Incarnation-p-lee when will be this released.? Thanks

**Comment by Incarnation-p-lee** [comment]
@aaaabhishek13 
We have one contributor working on this, it will be done in short future.
