### ISSUE TITLE
Support for time to live

### ISSUE THREAD

**Issue by julianzur** [Microsoft/spring-data-cosmosdb#75]
I'm looking for a convenient way to set the TTL parameter for my collection. Right know I think this is only possible from the browser - is this correct?

**Comment by Incarnation-p-lee** [comment]
@luly
Thanks for using and reporting. We may need to check with SDK library if they open this option to us. If so, we may support the TTL from `@Document`.

**Comment by Incarnation-p-lee** [comment]
@julianzur 
Could you please help to try the TTL feature in master branch, The feature will be available in next release.

**Comment by julianzur** [comment]
@Incarnation-p-lee 
Thanks for your support! I wanted to test your changes but I'm still on SpringBoot 1.5. Will this feature also be ported to the 1.5 branch?

**Comment by Incarnation-p-lee** [comment]
@julianzur 
OK, we can do that with cherry-pick. But that feature may available in next release for spring-boot 1.5.x.
Thanks for you information,

**Comment by julianzur** [comment]
@Incarnation-p-lee 
Can you give an ETA on when I can expect the change to be released for 1.5.x? Thanks. :)

**Comment by julianzur** [comment]
@Incarnation-p-lee 
I cherry-picked the changes to the 0.1.x-branch. As I don't have the permission to push to this repo, I uploaded the diff as a txt file and attach it to this comment. Hope this helps. Thanks!

[patch.txt](https://github.com/Microsoft/spring-data-cosmosdb/files/1927585/patch.txt)

**Comment by Incarnation-p-lee** [comment]
@julianzur 
Thanks very much for you contribution. It seems open the PR to public. I am not sure that permission issue. Could you please shared how to do that cherry-pick ?

**Comment by julianzur** [comment]
@Incarnation-p-lee 
Sorry, this is my first change to a public repo - maybe I'm misunderstanding the process. I am allowed to open a pull request - but I am not allowed to **push** local changes to the repo. 

> Pull requests let you tell others about changes you've **pushed** to a repository on GitHub. 
https://help.github.com/articles/about-pull-requests/

So, I cloned the repo, switched to the "0.1.x" branch and cherry-picked the changes from master. After resolving the conflicts, I endet up with a change set that I was not allowed to push back to the repo. That's why I stored them as a diff and uploaded them to this disucssion. 
Hope this makes sense.

**Comment by Incarnation-p-lee** [comment]
@julianzur 
Thanks for you time and work. Yeah, the process is almost like what you done. But a little different after resolving the conflicts. All developers include me are not allowed to push PR directed to this repo. We use PR mode. You can follow the step I list below.

* cherry-pick and fix conflict
* run test locally
* If all test passed, push you change to you forked repo.
* After all, create the PR to original repo from your forked repo.

Could you please help to have a try? Any problem please feel free to contact us. ;)

**Comment by julianzur** [comment]
Hey @Incarnation-p-lee! 
Will there be a 0.1.x release that contains the cherry picked changes any time soon?

**Comment by Incarnation-p-lee** [comment]
Yes, the next release of 0.1.x will cover that part. I will info you if ready.
